import {
  PhoneCall,
  Wifi,
  Tv,
  Lightbulb,
  BookOpenCheck,
  Gift,
  LayoutDashboard,
  Boxes,
  Wallet,
  UserCog,
  CircleDollarSign,
  User,
  Bell,
  Home,
  Settings,
} from "lucide-react";

export const services = [
  {
    id: 1,
    name: "Airtime",
    description: "Buy airtime for your phone",
    icon: PhoneCall,
    link: "/services/airtime",
    textColor: "text-green-500",
    bgColor: "bg-green-500/10",
    shadowColor: "shadow-green-500/10",
    borderColor: "border-green-500/10",
  },
  {
    id: 2,
    name: "Data",
    description: "Buy data bundles easily",
    icon: Wifi,
    link: "/services/data",
    textColor: "text-blue-500",
    bgColor: "bg-blue-500/10",
    shadowColor: "shadow-blue-500/10",
    borderColor: "border-blue-500/10",
  },
  {
    id: 3,
    name: "Cable",
    description: "Subscribe to DSTV, GOTV, Startimes",
    icon: Tv,
    link: "/services/cable",
    textColor: "text-purple-500",
    bgColor: "bg-purple-500/10",
    shadowColor: "shadow-purple-500/10",
    borderColor: "border-purple-500/10",
  },
  {
    id: 4,
    name: "Electricity",
    description: "Pay electricity bills (PHED, IKEDC, etc.)",
    icon: Lightbulb,
    link: "/services/electricity",
    textColor: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    shadowColor: "shadow-yellow-500/10",
    borderColor: "border-yellow-500/10",
  },
  {
    id: 5,
    name: "Education",
    description: "Buy WAEC or NECO scratch pins",
    icon: BookOpenCheck,
    link: "/services/education",
    textColor: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    shadowColor: "shadow-cyan-500/10",
    borderColor: "border-cyan-500/10",
  },
  {
    id: 6,
    name: "Gift Card",
    description: "Redeem gift cards easily",
    icon: Gift,
    link: "/services/gift-card",
    textColor: "text-rose-500",
    bgColor: "bg-rose-500/10",
    shadowColor: "shadow-rose-500/10",
    borderColor: "border-rose-500/10",
  },
];

export const menuItems = [
  {
    id: 1,
    name: "Dashboard",
    icon: LayoutDashboard,
    link: "/dashboard",
  },
  {
    id: 2,
    name: "Services",
    icon: Boxes,
    link: "/services",
  },
  {
    id: 4,
    name: "Wallet",
    icon: Wallet,
    link: "/wallet",
  },
  {
    id: 3,
    name: "Transactions",
    icon: CircleDollarSign,
    link: "/transactions",
  },
  {
    id: 5,
    name: "Support",
    icon: UserCog,
    link: "/profile",
  },
  {
    id: 6,
    name: "Profile",
    icon: UserCog,
    link: "/profile",
  },
];

export const adminMenuItems = [
  {
    id: 1,
    name: "Overview",
    icon: LayoutDashboard,
    link: "/admin/overview",
  },
  {
    id: 2,
    name: "Users",
    icon: User,
    link: "/admin/users",
  },

  {
    id: 3,
    name: "Data Plans",
    icon: BookOpenCheck,
    link: "/admin/data-plans",
  },
  {
    id: 4,
    name: "Notifications",
    icon: Bell,
    link: "/admin/notifications",
  },
  {
    id: 5,
    name: "Settings",
    icon: Settings,
    link: "/admin/settings",
  },
  {
    id: 6,
    name: "Home",
    icon: Home,
    link: "/dashboard",
  },
];

export const networkProviders = [
  {
    id: 1,
    name: "MTN",
    image: "/mtn.svg",
  },
  {
    id: 3,
    name: "Glo",
    image: "/glo.svg",
  },
  {
    id: 4,
    name: "9mobile",
    image: "/9mobile.svg",
  },
  {
    id: 2,
    name: "Airtel",
    image: "/airtel.svg",
  },
];

export const transactions = [
  {
    id: crypto.randomUUID(),
    amount: 100,
    status: "success",
    description: "Funding wallet",
    type: "credit",
    recipient: "08137411111",
    date: new Date(),
  },
  {
    id: crypto.randomUUID(),
    amount: 100,
    status: "success",
    description: "Mtn Airtime",
    type: "debit",
    recipient: "08137411111",
    date: new Date(),
  },
  {
    id: crypto.randomUUID(),
    amount: 400,
    status: "failed",
    description: "Airtel Data",
    type: "debit",
    recipient: "08137411111",
    date: new Date(),
  },
];

export const dataPlans: DataPlan[] = [
  // MTN
  {
    planId: 36,
    days: 30,
    network: "MTN",
    planType: "monthly",
    volume: 1,
    price: 690,
    extension: "GB",
    planName: "MTN Monthly 1GB",
  },
  {
    planId: 37,
    days: 30,
    network: "MTN",
    planType: "monthly",
    volume: 2,
    price: 1380,
    extension: "GB",
    planName: "MTN Monthly 2GB",
  },
  {
    planId: 38,
    days: 30,
    network: "MTN",
    planType: "monthly",
    volume: 3,
    price: 2070,
    extension: "GB",
    planName: "MTN Monthly 3GB",
  },
  {
    planId: 39,
    days: 30,
    network: "MTN",
    planType: "monthly",
    volume: 5,
    price: 3450,
    extension: "GB",
    planName: "MTN Monthly 5GB",
  },
  {
    planId: 135,
    days: 1,
    network: "MTN",
    planType: "daily",
    volume: 75,
    price: 76,
    extension: "MB",
    planName: "MTN Daily 75MB",
  },
  {
    planId: 136,
    days: 1,
    network: "MTN",
    planType: "daily",
    volume: 110,
    price: 100,
    extension: "MB",
    planName: "MTN Daily 110MB",
  },
  {
    planId: 137,
    days: 1,
    network: "MTN",
    planType: "daily",
    volume: 230,
    price: 200,
    extension: "MB",
    planName: "MTN Daily 230MB",
  },
  {
    planId: 138,
    days: 7,
    network: "MTN",
    planType: "weekly",
    volume: 500,
    price: 550,
    extension: "MB",
    planName: "MTN Weekly 500MB",
  },
  // Airtel
  {
    planId: 117,
    days: 30,
    network: "Airtel",
    planType: "monthly",
    volume: 2,
    price: 1500,
    extension: "GB",
    planName: "Airtel Monthly 2GB",
  },
  {
    planId: 118,
    days: 30,
    network: "Airtel",
    planType: "monthly",
    volume: 3,
    price: 2250,
    extension: "GB",
    planName: "Airtel Monthly 3GB",
  },
  {
    planId: 119,
    days: 30,
    network: "Airtel",
    planType: "monthly",
    volume: 4,
    price: 3000,
    extension: "GB",
    planName: "Airtel Monthly 4GB",
  },
];
